import { getVaccinationCertificate } from "@/lib/portal-actions"
import { notFound } from "next/navigation"
import { format } from "date-fns"

export default async function CertificatePage({ params }: { params: { id: string } }) {
    const vax = await getVaccinationCertificate(params.id)

    if (!vax) return notFound()

    return (
        <div className="min-h-screen bg-gray-100 p-8 flex justify-center items-start">
            <div className="bg-white p-12 max-w-2xl w-full shadow-lg print:shadow-none print:w-full">
                {/* Header */}
                <div className="text-center border-b-2 border-gray-100 pb-8 mb-8">
                    <h1 className="text-3xl font-serif font-bold text-primary-900 mb-2">Vaccination Certificate</h1>
                    <p className="text-gray-500">{vax.pet.clinic.name}</p>
                    <p className="text-sm text-gray-400">{vax.pet.clinic.address}, {vax.pet.clinic.city}</p>
                </div>

                {/* Pet Details */}
                <div className="grid grid-cols-2 gap-8 mb-8">
                    <div>
                        <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-1">Patient</h3>
                        <p className="text-xl font-bold">{vax.pet.name}</p>
                        <p className="text-gray-600">{vax.pet.species} • {vax.pet.breed}</p>
                        <p className="text-gray-600">{vax.pet.gender} • {vax.pet.color || 'N/A'}</p>
                    </div>
                    <div className="text-right">
                        <h3 className="text-sm font-semibold text-gray-400 uppercase tracking-wider mb-1">Owner</h3>
                        <p className="text-xl font-bold">{vax.pet.owner.firstName} {vax.pet.owner.lastName}</p>
                        <p className="text-gray-600">{vax.pet.owner.email}</p>
                    </div>
                </div>

                {/* Vaccination Details */}
                <div className="bg-gray-50 p-8 rounded-xl border border-gray-100 mb-8">
                    <div className="grid grid-cols-2 gap-y-6">
                        <div>
                            <p className="text-sm text-gray-500">Vaccine Name</p>
                            <p className="text-lg font-semibold">{vax.vaccineName}</p>
                        </div>
                        <div>
                            <p className="text-sm text-gray-500">Date Administered</p>
                            <p className="text-lg font-semibold">{format(new Date(vax.dateGiven), 'MMMM d, yyyy')}</p>
                        </div>
                        <div>
                            <p className="text-sm text-gray-500">Batch Number</p>
                            <p className="font-mono">{vax.batchNumber || 'N/A'}</p>
                        </div>
                        <div>
                            <p className="text-sm text-gray-500">Next Due Date</p>
                            <p className="font-semibold text-primary-700">
                                {vax.nextDueDate ? format(new Date(vax.nextDueDate), 'MMMM d, yyyy') : 'N/A'}
                            </p>
                        </div>
                        <div className="col-span-2">
                            <p className="text-sm text-gray-500">Administered By</p>
                            <p className="font-medium">{vax.givenBy}</p>
                        </div>
                    </div>
                </div>

                {/* Footer / Signature */}
                <div className="mt-16 pt-8 border-t border-gray-200 flex justify-between items-end">
                    <div className="text-sm text-gray-400">
                        <p>Generated by VetFlow</p>
                        <p>Certificate ID: {vax.id}</p>
                    </div>
                    <div className="text-center">
                        <div className="w-48 border-b border-gray-300 mb-2"></div>
                        <p className="text-sm font-medium text-gray-600">Veterinarian Signature</p>
                    </div>
                </div>

                {/* Print Button (Hidden when printing) */}
                <div className="mt-8 text-center print:hidden">
                    <button
                        onClick={() => window.print()}
                        className="bg-primary-600 text-white px-6 py-2 rounded-lg hover:bg-primary-700 transition-colors"
                    >
                        Print Certificate
                    </button>
                </div>
            </div>
        </div>
    )
}
